SET FOREIGN_KEY_CHECKS = 0;

DELETE FROM `VersionDefect`;
DELETE FROM `VersionRequirement`;
DELETE FROM `VersionDocument`;
DELETE FROM `RequirementDocument`;
DELETE FROM `ActivityLog`;
DELETE FROM `Defect`;
DELETE FROM `DevTask`;
DELETE FROM `RequirementChange`;
DELETE FROM `ProjectDocument`;
DELETE FROM `ReleaseVersion`;
DELETE FROM `ProjectMember`;
DELETE FROM `Requirement`;
DELETE FROM `Project`;

SET FOREIGN_KEY_CHECKS = 1;

DELETE FROM `Dictionary`
WHERE (`type` = 'REQUIREMENT_STATUS' AND `code` IN ('TESTING', 'READY_TO_RELEASE', 'RELEASED'))
   OR (`type` = 'TASK_STATUS' AND `code` IN ('DONE', 'BLOCKED', 'CANCELED'))
   OR (`type` = 'DEFECT_STATUS' AND `code` IN ('TO_ASSIGN', 'DOING', 'TO_VERIFY', 'REOPENED', 'REJECTED', 'DEFERRED'));

ALTER TABLE `Requirement`
  ADD COLUMN `launchStatus` ENUM('TO_RELEASE', 'RELEASED') NOT NULL DEFAULT 'TO_RELEASE' AFTER `status`,
  MODIFY `status` ENUM('TO_REVIEW', 'APPROVED', 'REJECTED', 'NEEDS_SUPPLEMENT', 'DEFERRED', 'DEVELOPING', 'COMPLETED', 'CANCELED', 'CHANGE', 'OPTIMIZATION') NOT NULL DEFAULT 'TO_REVIEW';

ALTER TABLE `DevTask`
  MODIFY `status` ENUM('TODO', 'DOING', 'TO_TEST', 'TESTING', 'TEST_PASSED', 'CLOSED') NOT NULL DEFAULT 'TODO';

ALTER TABLE `Defect`
  DROP FOREIGN KEY `Defect_requirementId_fkey`,
  ADD COLUMN `taskId` INTEGER NOT NULL AFTER `projectId`,
  DROP COLUMN `requirementId`,
  MODIFY `status` ENUM('TO_FIX', 'FIXING', 'FIXED', 'VERIFIED', 'CLOSED') NOT NULL DEFAULT 'TO_FIX';

ALTER TABLE `Defect`
  ADD CONSTRAINT `Defect_taskId_fkey` FOREIGN KEY (`taskId`) REFERENCES `DevTask`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
