ALTER TABLE `DevTask`
  ADD COLUMN `testerId` INTEGER NULL;

ALTER TABLE `Defect`
  ADD COLUMN `testerId` INTEGER NULL;

ALTER TABLE `DevTask`
  ADD CONSTRAINT `DevTask_testerId_fkey` FOREIGN KEY (`testerId`) REFERENCES `Person`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `Defect`
  ADD CONSTRAINT `Defect_testerId_fkey` FOREIGN KEY (`testerId`) REFERENCES `Person`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
